apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restapi.fullname" . }}
  labels:
    {{- include "restapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "restapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "restapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: test-ghcr
      {{- end }}
      serviceAccountName: {{ include "restapi.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP