apiVersion: batch/v1
kind: Job
metadata:
  name: job-example
spec:
  completions: 4
#   parallelism: 2
#   activeDeadlineSeconds: 15
  template:
    spec:
      containers:
      - name: centos-container
        image: centos:7
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello World'; sleep 3; echo 'Bye'"
      restartPolicy: Never
  #     restartPolicy: OnFailure
  # backoffLimit: 3