name: Commit For ArgoCD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:

  CD:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        ref: ArgoCD

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: print
      run: |
        pwd
        ls
        ls helm-folder

    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'helm-folder/values.yaml'
        propertyPath: 'backend.version'
        value: ${{ env.RELEASE_VERSION }}
        branch: ArgoCD
        message: 'Update Image Version to ${{ env.RELEASE_VERSION }}' 