name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Docker meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: mrxminsoo/restapi
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: print
      run: |
        echo $steps.meta.outputs.tags
        echo $steps.meta.outputs

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}